### ISSUE TITLE
Crash in Select().ToList()

### ISSUE THREAD

**Issue by aalmada** [reegeek/StructLinq#107]
LinqBenchmarks is crashing when executing the [ArrayInt32SelectToList](https://github.com/NetFabric/LinqBenchmarks/blob/b307cf0b08c15ae39dc8caf97651badbdb783413/LinqBenchmarks/Array/Int32/ArrayInt32SelectToList.cs#L85) benchmarks. Unfortunately, the stack trace is not very helpful.

I'm using .NET 6.0 Preview 5.

**Comment by reegeek** [comment]
If you have a crash, I think is due to list layout change in net 6.

**Comment by reegeek** [comment]
@aalmada could you try with 0.26.4 ?
It should be ok.

**Comment by aalmada** [comment]
Thanks for checking. Sorry, but it was too late last night.
It's strange but it still crashes when running the benchmark but it works if I execute the same code in a console app.
This is the output I'm getting:

```
// **************************
// Benchmark: ArrayInt32SelectToList.StructLinq: .NET 6(EnvironmentVariables=COMPlus_ReadyToRun=0,COMPlus_TC_QuickJitForLoops=1,COMPlus_TieredPGO=1, Runtime=.NET 6.0) [Count=100]
// *** Execute ***
// Launch: 1 / 1
// Execute: dotnet "f584b1ef-1d13-4162-9857-e1f586e0d8af.dll" --benchmarkName "LinqBenchmarks.Array.Int32.ArrayInt32SelectToList.StructLinq(Count: 100)" --job ".NET 6" --benchmarkId 10 in C:\Projects\LinqBenchmarks\LinqBenchmarks\bi
n\Release\net6.0\f584b1ef-1d13-4162-9857-e1f586e0d8af\bin\Release\net6.0
// BeforeAnythingElse

// Benchmark Process Environment Information:
// Runtime=.NET 6.0.0 (6.0.21.30105), X64 RyuJIT
// GC=Concurrent Workstation
// Job: .NET 6

OverheadJitting  1: 1 op, 341300.00 ns, 341.3000 us/op
WorkloadJitting  1: 1 op, 40450400.00 ns, 40.4504 ms/op

WorkloadPilot    1: 2 op, 11700.00 ns, 5.8500 us/op
WorkloadPilot    2: 3 op, 5300.00 ns, 1.7667 us/op
WorkloadPilot    3: 4 op, 9300.00 ns, 2.3250 us/op
WorkloadPilot    4: 5 op, 6800.00 ns, 1.3600 us/op
WorkloadPilot    5: 6 op, 7900.00 ns, 1.3167 us/op
WorkloadPilot    6: 7 op, 9600.00 ns, 1.3714 us/op
WorkloadPilot    7: 8 op, 10200.00 ns, 1.2750 us/op
WorkloadPilot    8: 9 op, 13900.00 ns, 1.5444 us/op
WorkloadPilot    9: 10 op, 12500.00 ns, 1.2500 us/op
WorkloadPilot   10: 11 op, 13300.00 ns, 1.2091 us/op
WorkloadPilot   11: 12 op, 14200.00 ns, 1.1833 us/op
WorkloadPilot   12: 13 op, 15100.00 ns, 1.1615 us/op
WorkloadPilot   13: 14 op, 16000.00 ns, 1.1429 us/op
WorkloadPilot   14: 15 op, 17100.00 ns, 1.1400 us/op
WorkloadPilot   15: 16 op, 18900.00 ns, 1.1812 us/op
WorkloadPilot   16: 32 op, 35400.00 ns, 1.1062 us/op
WorkloadPilot   17: 64 op, 69000.00 ns, 1.0781 us/op
WorkloadPilot   18: 128 op, 134900.00 ns, 1.0539 us/op
WorkloadPilot   19: 256 op, 322100.00 ns, 1.2582 us/op
WorkloadPilot   20: 512 op, 536100.00 ns, 1.0471 us/op
WorkloadPilot   21: 1024 op, 1181000.00 ns, 1.1533 us/op
WorkloadPilot   22: 2048 op, 2403100.00 ns, 1.1734 us/op
WorkloadPilot   23: 4096 op, 6042900.00 ns, 1.4753 us/op
WorkloadPilot   24: 8192 op, 9048000.00 ns, 1.1045 us/op
WorkloadPilot   25: 16384 op, 20063800.00 ns, 1.2246 us/op
WorkloadPilot   26: 32768 op, 42751000.00 ns, 1.3047 us/op

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at LinqBenchmarks.Array.Int32.ArrayInt32SelectToList.StructLinq() in C:\Projects\LinqBenchmarks\LinqBenchmarks\Array\Int32\ArrayInt32SelectToList.cs:line 86
   at BenchmarkDotNet.Autogenerated.Runnable_10.WorkloadActionNoUnroll(Int64 invokeCount) in C:\Projects\LinqBenchmarks\LinqBenchmarks\bin\Release\net6.0\f584b1ef-1d13-4162-9857-e1f586e0d8af\f584b1ef-1d13-4162-9857-e1f586e0d8af.notc
s:line 7825
   at BenchmarkDotNet.Engines.Engine.RunIteration(IterationData data) in BenchmarkDotNet.dll:token 0x600098a+0xb9
   at BenchmarkDotNet.Engines.EngineStage.RunIteration(IterationMode mode, IterationStage stage, Int32 index, Int64 invokeCount, Int32 unrollFactor) in BenchmarkDotNet.dll:token 0x60009e4+0x38
   at BenchmarkDotNet.Engines.EnginePilotStage.RunAuto() in BenchmarkDotNet.dll:token 0x60009dc+0x14
   at BenchmarkDotNet.Engines.EnginePilotStage.Run() in BenchmarkDotNet.dll:token 0x60009db+0x36
   at BenchmarkDotNet.Engines.Engine.Run() in BenchmarkDotNet.dll:token 0x6000989+0x38
   at BenchmarkDotNet.Autogenerated.Runnable_10.Run(IHost host, String benchmarkName) in C:\Projects\LinqBenchmarks\LinqBenchmarks\bin\Release\net6.0\f584b1ef-1d13-4162-9857-e1f586e0d8af\f584b1ef-1d13-4162-9857-e1f586e0d8af.notcs:li
ne 7504
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in System.Private.CoreLib.dll:token 0x6004ea5+0x23
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters) in System.Private.CoreLib.dll:token 0x6004da9+0x0
   at BenchmarkDotNet.Autogenerated.UniqueProgramName.AfterAssemblyLoadingAttached(String[] args) in C:\Projects\LinqBenchmarks\LinqBenchmarks\bin\Release\net6.0\f584b1ef-1d13-4162-9857-e1f586e0d8af\f584b1ef-1d13-4162-9857-e1f586e0d
8af.notcs:line 66
// AfterAll
// Benchmark Process 19348 has exited with code -1
Unhandled exception. System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException() in System.Linq.dll:token 0x600041e+0xa
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.Execute(ILogger logger, BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, IToolchain toolchain, BuildResult buildResult, IResolver resolver) in BenchmarkDotNet.dll:token 0x60004
1e+0x0
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.RunCore(BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, ILogger logger, IResolver resolver, BuildResult buildResult) in BenchmarkDotNet.dll:token 0x600041d+0x3f
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.Run(BenchmarkRunInfo benchmarkRunInfo, Dictionary`2 buildResults, IResolver resolver, ILogger logger, List`1 artifactsToCleanup, String resultsFolderPath, String logFilePath, Starte
dClock& runChronometer) in BenchmarkDotNet.dll:token 0x6000418+0x11b
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.Run(BenchmarkRunInfo[] benchmarkRunInfos) in BenchmarkDotNet.dll:token 0x6000417+0x20f
   at BenchmarkDotNet.Running.BenchmarkSwitcher.RunWithDirtyAssemblyResolveHelper(String[] args, IConfig config, Boolean askUserForInput) in BenchmarkDotNet.dll:token 0x6000448+0x131
   at BenchmarkDotNet.Running.BenchmarkSwitcher.Run(String[] args, IConfig config) in BenchmarkDotNet.dll:token 0x6000447+0x6
   at LinqBenchmarks.Program.Main(String[] args) in C:\Projects\LinqBenchmarks\LinqBenchmarks\Program.cs:line 43
// * Artifacts cleanup *
```

**Comment by aalmada** [comment]
By the way, is there a change in the List<> internal structure? I'm using the same cast as you and all the unit tests are still green.

**Comment by reegeek** [comment]
They are no change in the layout.

Until now, structlinq used the wrong layout in net 6.

I have a PR for targeting net 6, but I have a another error on my CI stack.

It should solve your problems when structlinq explicitly handle net6.

**Comment by reegeek** [comment]
Hi @aalmada can you try the last release (0.27.0) ?
I handle properly net60

**Comment by aalmada** [comment]
@reegeek Strange. It still crashes. 🤔
If I execute the exact same code without BechmarkDotNet, it doesn't crash.
It only crashes when executing benchmarks for StructLinq queries. 
I don't know what to try next... 🤯

**Comment by reegeek** [comment]
Is it working with previous preview version of net60 ?

**Comment by aalmada** [comment]
Good question. I now tried targetting .NET 5, running the job in .NET 5, and it works.
Notice on previous results that I was targeting .NET 5 but running the job in .NET 6: https://github.com/NetFabric/LinqBenchmarks/blob/master/Results/Array.Int32.ArrayInt32SelectToList.md
Did something change for .NET 6 Preview 5?
Are you using Preview 5?

**Comment by reegeek** [comment]
Hi, github actions using the following version 6.0.100-preview.5.21302.13, and all  tests are ok.

If i understand well, if benchmark.net is targeting .net5, all benchmarks are ok but if it is targeting .net6, you are some weird errors.
Maybe benchmark.net is no handle perfectly net60.

**Comment by aalmada** [comment]
Maybe. It's just strange that only happens for StructLinq but only when benchmarking.
I'm going to close this as I have no idea what's going on...
